export enum BlockNames {
  HERO_PRIMARY = 'ComponentHeroHeroHome',
  HERO_SECONDARY = 'ComponentHeroHeroSecondary',
  SLICE_CAROUSEL = 'ComponentSliceCarousel',
  DOUBLE_COLUMN_TEXT = 'ComponentContentBlockTwoColumnTextBlock',
  CENTER_CONTENT_BLOCK = 'ComponentContentBlockCenterContentBlock',
  CONTACT_BLOCK = 'ComponentSliceContactCareerOpportunityBlock',
  VIDEO_FRAME = 'ComponentSliceSliceVideoFrame',
  RICH_TEXT_BLOCK = 'ComponentSliceSliceRichTextBlock',
  TESTIMONIAL = 'ComponentContentBlockTestimonialBlock',
  LOGO_BLOCK = 'ComponentSliceLogoBlock',
  LOGO_BLOCK_WITH_TESTIMONIAL = 'ComponentSliceLogoBlockWithTestimonial',
  CONTENT_LIST_SECTION = 'ComponentSliceContentListSection',
  SERVICE_CONTENT_LIST_SECTION = 'ComponentSliceSliceServiceContentList',
  CUSTOM_CARD_LIST = 'ComponentSliceSliceCustomCardList',
  CARD_LIST_PAGINATION = 'ComponentSliceSliceCardList',
  CASESTUDY_CAROUSEL = 'ComponentSliceCaseStudyCarouselBlock',
  FEATURED_ARTICLE = 'ComponentSliceSliceFeaturedArticle',
  RICH_TEXT_WITH_INFO = 'ComponentSliceSliceRichTextWithInfo',
  REDIRECT_BUTTON = 'ComponentButtonButton',
  BRANDING_SLIDER = 'ComponentSliderBrandingSlider',
  FORM = 'ComponentFormForm',
  FAQ = 'ComponentSliceSliceFaq',
}
