// External Imports
import Head from 'next/head';
import { redirectTo500page } from '@src/utils/strapi';
import client from '@root/apollo-client';
import { PageBySlug } from '@src/query';
import dynamic from 'next/dynamic';
import { ILayoutProps } from '@src/types/__layout';
import Loading from '@src/components/root/loading';
import { getFooterInfo, getGlobalInfo } from '@src/query/pages-data';
import { IPageProps } from '@src/types/pages/about';
import { IContext, IPodcasts } from '@src/types/pages';

const Podcasts = dynamic<IPodcasts>(
  import('@src/components/pages/podcasts').then((module) => module.Podcasts),
  { loading: () => <Loading /> }
);
const Layout = dynamic<ILayoutProps>(
  import('@src/components/__layout').then((module) => module.Layout),
  { loading: () => <Loading /> }
);
const Podcast = ({
  pageInfo,
  globalInfo,
  footerInfo,
  locale,
  preview,
}: IPageProps) => {
  return (
    <>
      <Head>
        <title>EastSide | Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="googlebot" content="noindex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout globalInfo={globalInfo} footerInfo={footerInfo} preview={preview}>
        <div>
          {/* The dynamic blocks will be rendered here */}
          <Podcasts heroProps={pageInfo.block[0]} locale={locale} />
        </div>
      </Layout>
    </>
  );
};
export async function getStaticProps(context: IContext) {
  let { locale } = context;
  let pageInfo, globalInfo, footerInfo;
  if (!locale) locale = 'en';
  try {
    /* Page Data Fetch */
    const { data: pageData } = await client.query({
      query: PageBySlug('podcast', locale),
    });
    if (pageData.pages.data.length) {
      pageInfo = pageData.pages.data[0].attributes;
    } else {
      return redirectTo500page();
    }

    /* Global Info Fetch */
    globalInfo = await getGlobalInfo(locale, client);
    /* Footer Info Fetch */
    footerInfo = await getFooterInfo(locale, client);
    if (!globalInfo || !footerInfo) return redirectTo500page();
    return {
      props: {
        pageInfo,
        globalInfo,
        footerInfo,
        locale,
        preview: context.preview || false,
      },
      revalidate: context.preview ? 1 : 120,
    };
  } catch (error) {
    return redirectTo500page();
  }
}
export default Podcast;
