// External Imports
import Head from 'next/head';
import { redirectTo500page } from '@src/utils/strapi';
import client from '@root/apollo-client';
import { PageBySlug } from '@src/query';
import {
  getCaseStudyByCategory,
  getFooterInfo,
  getGlobalInfo,
  getServicesList,
} from '@src/query/pages-data';
import dynamic from 'next/dynamic';
import Loading from '@src/components/root/loading';
import { ILayoutProps } from '@src/types/__layout';
import { IPageProps } from '@src/types/pages/about';
import { IContext } from '@src/types/pages';

const Layout = dynamic<ILayoutProps>(
  import('@src/components/__layout').then((module) => module.Layout),
  { loading: () => <Loading /> }
);
const BlockManagerComp = dynamic(
  () => import('@src/components/blockManager/block-manager-comp'),
  { loading: () => <Loading /> }
);
const Home = ({
  pageInfo,
  globalInfo,
  footerInfo,
  caseStudies,
  servicesList,
  preview,
}: IPageProps) => {
  // redecorate data
  const stringPageData = JSON.stringify(pageInfo);
  const parsedData = JSON.parse(stringPageData);
  parsedData.block.map((ele: any, ind: number) => {
    if (ele.__typename === 'ComponentSliceCaseStudyCarouselBlock') {
      ele.caseStudies = caseStudies;
    }
    if (ele.__typename === 'ComponentSliceSliceServiceContentList') {
      ele.contentBlockList = servicesList;
    }
  });
  return (
    <>
      <Head>
        <title>Plan And Launch | Plan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="googlebot" content="noindex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout globalInfo={globalInfo} footerInfo={footerInfo} preview={preview}>
        <div>
          {/* The dynamic blocks will be rendered here */}
          <BlockManagerComp blockData={parsedData.block} />
        </div>
      </Layout>
    </>
  );
};
export async function getStaticProps(context: IContext) {
  let { locale } = context;
  let pageInfo, globalInfo, footerInfo, caseStudies, servicesList;
  if (!locale) locale = 'en';
  try {
    /* Page Data Fetch */
    const { data } = await client.query({
      query: PageBySlug('plan-launch', locale),
    });
    if (data.pages.data.length) {
      pageInfo = data.pages.data[0].attributes;
    } else {
      return redirectTo500page();
    }
    /* Global Info Fetch */
    globalInfo = await getGlobalInfo(locale, client);
    /* Footer Info Fetch */
    footerInfo = await getFooterInfo(locale, client);
    // case studies data
    caseStudies = await getCaseStudyByCategory(locale, client, pageInfo.block);
    // service list data by category
    servicesList = await getServicesList(locale, client, pageInfo.block);
    if (!globalInfo || !footerInfo) return redirectTo500page();
    return {
      props: {
        pageInfo,
        globalInfo,
        footerInfo,
        caseStudies: !!caseStudies ? caseStudies.caseStudyLists : null,
        servicesList:
          !!servicesList && !!servicesList.length ? servicesList : null,
        preview: context.preview || false,
      },
      revalidate: context.preview ? 1 : 120,
    };
  } catch (error) {
    return redirectTo500page();
  }
}
export default Home;
