import client from '@root/apollo-client';
import Loading from '@src/components/root/loading';
import { PageBySlug } from '@src/query';
import { getFooterInfo, getGlobalInfo } from '@src/query/pages-data';
import { IBlogs, IContext } from '@src/types/pages';
import { IPageProps } from '@src/types/pages/about';
import { ILayoutProps } from '@src/types/__layout';
import { redirectTo500page } from '@src/utils';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const BlogsPage = dynamic<IBlogs>(
  import('@src/components/pages/blogs').then((module) => module.BlogsPage),
  { loading: () => <Loading /> }
);
const Layout = dynamic<ILayoutProps>(
  import('@src/components/__layout').then((module) => module.Layout),
  { loading: () => <Loading /> }
);
const BlogList = ({
  pageInfo,
  globalInfo,
  footerInfo,
  locale,
  preview,
}: IPageProps) => {
  return (
    <>
      <Head>
        <title>EastSide | Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex,nofollow" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout globalInfo={globalInfo} footerInfo={footerInfo} preview={preview}>
        <BlogsPage
          heroProps={pageInfo.block[0]}
          featuredBlog={pageInfo.block[1]}
          blogListInfo={pageInfo.block[2]}
          locale={locale}
        />
      </Layout>
    </>
  );
};
export async function getStaticProps(context: IContext) {
  let { locale } = context;
  let pageInfo, globalInfo, footerInfo;
  if (!locale) locale = 'en';
  try {
    const { data: pageData } = await client.query({
      query: PageBySlug('blog', locale),
    });
    if (pageData.pages.data.length) {
      pageInfo = pageData.pages.data[0].attributes;
    } else {
      return redirectTo500page();
    }

    /* Global Info Fetch */
    globalInfo = await getGlobalInfo(locale, client);
    /* Footer Info Fetch */
    footerInfo = await getFooterInfo(locale, client);
    if (!globalInfo || !footerInfo) return redirectTo500page();
    return {
      props: {
        pageInfo,
        globalInfo,
        footerInfo,
        locale,
        preview: context.preview || false,
      },
      revalidate: context.preview ? 1 : 120,
    };
  } catch (error) {
    return redirectTo500page();
  }
}
export default BlogList;
