import dynamic from 'next/dynamic';
import { redirectTo500page } from '@src/utils/strapi';
import client from '@root/apollo-client';
import { PageBySlug } from '@src/query';
import Head from 'next/head';
import {
  getCaseStudyByCategory,
  getFooterInfo,
  getGlobalInfo,
} from '@src/query/pages-data';
import Loading from '@src/components/root/loading';
import { ILayoutProps } from '@src/types/__layout';
import { IPageProps } from '@src/types/pages/about';

const Layout = dynamic<ILayoutProps>(
  import('@src/components/__layout').then((module) => module.Layout),
  { loading: () => <Loading /> }
);
const BlockManagerComp = dynamic(
  () => import('@src/components/blockManager/block-manager-comp'),
  { loading: () => <Loading /> }
);

const Page = ({
  pageInfo,
  globalInfo,
  footerInfo,
  caseStudies,
  preview,
}: IPageProps) => {
  // redecorate data
  const stringPageData = JSON.stringify(pageInfo);
  const parsedData = JSON.parse(stringPageData);
  parsedData.block.map((ele: any, ind: number) => {
    if (ele.__typename === 'ComponentSliceCaseStudyCarouselBlock') {
      ele.caseStudies = caseStudies;
    }
  });
  let footerHeaderData;
  if (pageInfo.footerFormInfo) {
    footerHeaderData = pageInfo.footerFormInfo;
  }

  return (
    <>
      <Head>
        <title>EastSide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="googlebot" content="noindex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        globalInfo={globalInfo}
        footerInfo={footerInfo}
        footerHeaderInfo={footerHeaderData}
        preview={preview}
      >
        <div>
          {/* The dynamic blocks will be rendered here */}
          <BlockManagerComp blockData={parsedData.block} />
        </div>
      </Layout>
    </>
  );
};

export async function getServerSideProps(context: {
  res: any;
  query: { slug: string };
  locale: string;
  defaultLocale: string;
  preview: boolean | null;
}) {
  let { slug } = context.query;
  let { locale, defaultLocale } = context;
  let pageInfo, globalInfo, footerInfo, caseStudies;
  if (!locale) locale = defaultLocale;

  try {
    /* Page Data Fetch */
    const { data } = await client.query({
      query: PageBySlug(slug, locale),
    });
    if (data.pages.data.length) {
      pageInfo = data.pages.data[0].attributes;
    } else {
      return redirectTo500page();
    }
    /* Global Info Fetch */
    globalInfo = await getGlobalInfo(locale, client);
    /* Footer Info Fetch */
    footerInfo = await getFooterInfo(locale, client);
    // case studies data
    caseStudies = await getCaseStudyByCategory(locale, client, pageInfo.block);
    context.res.setHeader(
      'Cache-Control',
      'public, s-maxage=10, stale-while-revalidate=59'
    );
    if (!globalInfo || !footerInfo) return redirectTo500page();
    return {
      props: {
        pageInfo,
        globalInfo,
        footerInfo,
        caseStudies: !!caseStudies ? caseStudies.caseStudyLists : null,
        preview: context.preview || false,
      },
    };
  } catch (error) {
    return redirectTo500page();
  }
}

export default Page;
