// External Imports
import { useEffect } from 'react';
import Head from 'next/head';
import { redirectTo500page } from '@src/utils/strapi';
import client from '@root/apollo-client';
import { PageBySlug } from '@src/query';
import {
  getCaseStudyByCategory,
  getFooterInfo,
  getGlobalInfo,
} from '@src/query/pages-data';
import dynamic from 'next/dynamic';
import Loading from '@src/components/root/loading';
import { ILayoutProps } from '@src/types/__layout';
import { IPageProps } from '@src/types/pages/about';
import { IContext } from '@src/types/pages';

const Layout = dynamic<ILayoutProps>(
  import('@src/components/__layout').then((module) => module.Layout),
  { loading: () => <Loading /> }
);
const BlockManagerComp = dynamic(
  () => import('@src/components/blockManager/block-manager-comp'),
  { loading: () => <Loading /> }
);
const Home = ({
  pageInfo,
  globalInfo,
  footerInfo,
  caseStudies,
  preview,
}: IPageProps) => {
  // bug reporting tool gleap integration
  useEffect(() => {
    const gleapInitialize = async () => {
      const Gleap = (await import('gleap')).default;
      Gleap.initialize('SpeDbcQlDL7sVARdoownoaALL1zGLkjg');
    };
    gleapInitialize();
  }, []);
  // redecorate data
  const stringPageData = JSON.stringify(pageInfo);
  const parsedData = JSON.parse(stringPageData);
  parsedData.block.map((ele: any, ind: number) => {
    if (ele.__typename === 'ComponentSliceCaseStudyCarouselBlock') {
      ele.caseStudies = caseStudies;
    }
  });

  let footerHeaderData;
  if (pageInfo.footerFormInfo) {
    footerHeaderData = pageInfo.footerFormInfo;
  }
  return (
    <>
      <Head>
        <title>EastSide | Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:title"
          content="Eastside Co is one of the world’s most trusted and experienced Shopify Plus Partners"
        />
        <meta
          property="og:image"
          content="https://res.cloudinary.com/dktw59lc2/image/upload/v1669642837/EastSide-dev/images/Group_1050_49f2689987.png?width=178&height=23"
        />
        {/* <meta name="robots" content="noindex,nofollow" />
        <meta name="googlebot" content="noindex" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        globalInfo={globalInfo}
        footerInfo={footerInfo}
        footerHeaderInfo={footerHeaderData}
        preview={preview}
      >
        <div>
          {/* The dynamic blocks will be rendered here */}
          <BlockManagerComp blockData={parsedData.block} />
        </div>
      </Layout>
    </>
  );
};
export async function getStaticProps(context: IContext) {
  let { locale } = context;
  let pageInfo, globalInfo, footerInfo, caseStudies;
  if (!locale) locale = 'en';
  try {
    /* Page Data Fetch */
    const { data } = await client.query({
      query: PageBySlug('home', locale),
    });
    if (data.pages.data.length) {
      pageInfo = data.pages.data[0].attributes;
    } else {
      // return redirectTo500page();
    }

    /* Global Info Fetch */
    globalInfo = await getGlobalInfo(locale, client);
    /* Footer Info Fetch */
    footerInfo = await getFooterInfo(locale, client);
    // case studies data
    caseStudies = await getCaseStudyByCategory(locale, client, pageInfo.block);
    if (!globalInfo || !footerInfo) return redirectTo500page();
    return {
      props: {
        pageInfo,
        globalInfo,
        footerInfo,
        caseStudies: !!caseStudies ? caseStudies.caseStudyLists : null,
        preview: context.preview || false,
      },
      revalidate: context.preview ? 1 : 120,
    };
  } catch (error) {
    return redirectTo500page();
  }
}
export default Home;
