import client from '@root/apollo-client';
import Loading from '@src/components/root/loading';
import { CaseStudiesBySlug, CaseStudiesSlug } from '@src/query/case-study';
import { getFooterInfo, getGlobalInfo } from '@src/query/pages-data';
import { IContext } from '@src/types/pages';
import { IPageProps } from '@src/types/pages/about';
import { IPathContext } from '@src/types/pages/page';
import { ILayoutProps } from '@src/types/__layout';
import { redirectTo500page } from '@src/utils';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useRouter } from 'next/router';

const CaseStudyPage = dynamic<{ pageData: any }>(
  import('@src/components/pages/case-study').then(
    (module) => module.CaseStudyPage
  ),
  { loading: () => <Loading /> }
);
const Layout = dynamic<ILayoutProps>(
  import('@src/components/__layout').then((module) => module.Layout),
  { loading: () => <Loading /> }
);
const CaseStudy = ({
  globalInfo,
  footerInfo,
  caseStudies,
  preview,
}: IPageProps) => {
  const router = useRouter();
  if (router.isFallback) {
    return (
      <div className="container flex items-center h-screen">
        <Loading />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>EastSide | Case Study</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="googlebot" content="noindex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        globalInfo={globalInfo}
        footerInfo={footerInfo}
        footerHeaderInfo={caseStudies.attributes.footerFormInfo}
        preview={preview}
      >
        <CaseStudyPage pageData={caseStudies} />
      </Layout>
    </>
  );
};

export async function getStaticPaths(context: IPathContext) {
  let { defaultLocale, locales } = context;
  // fetch all case study slugs
  const { data } = await client.query({
    query: CaseStudiesSlug(defaultLocale),
  });
  const caseStudyData =
    !!data.caseStudyLists?.data && !!data.caseStudyLists.data.length
      ? data.caseStudyLists.data
      : [];
  const paths = caseStudyData.map((ele: { attributes: { slug: string } }) =>
    locales.map((loc: string) => {
      return {
        params: { slug: ele?.attributes.slug },
        locale: loc,
      };
    })
  );

  return {
    paths: paths.flat(),
    fallback: true,
  };
}
export async function getStaticProps(context: IContext) {
  let { locale } = context;
  let { slug } = context.params;
  let globalInfo, footerInfo, caseStudies;
  if (!locale) locale = 'en';
  try {
    // Fetch case study data by slug
    const { data: caseStudyData } = await client.query({
      query: CaseStudiesBySlug(slug, locale),
    });
    if (caseStudyData) {
      caseStudies = caseStudyData.caseStudyLists?.data[0];
    }
    /* Global Info Fetch */
    globalInfo = await getGlobalInfo(locale, client);
    /* Footer Info Fetch */
    footerInfo = await getFooterInfo(locale, client);
    if (!globalInfo || !footerInfo) return redirectTo500page();
    return {
      props: {
        globalInfo,
        footerInfo,
        caseStudies,
        preview: context.preview || false,
      },
      revalidate: context.preview ? 1 : 120,
    };
  } catch (error) {
    return redirectTo500page();
  }
}
export default CaseStudy;
