// External Imports
import Head from 'next/head';
import { redirectTo500page } from '@src/utils/strapi';
import client from '@root/apollo-client';
import { PageBySlug } from '@src/query';
import { getFooterInfo, getGlobalInfo } from '@src/query/pages-data';
import { ILayoutProps } from '@src/types/__layout';
import dynamic from 'next/dynamic';
import Loading from '@src/components/root/loading';
import { IPageProps } from '@src/types/pages/about';
import { ICaseStudyList, IContext } from '@src/types/pages';

const CaseStudyList = dynamic<ICaseStudyList>(
  import('@src/components/pages/case-study').then(
    (module) => module.CaseStudyList
  ),
  { loading: () => <Loading /> }
);
const Layout = dynamic<ILayoutProps>(
  import('@src/components/__layout').then((module) => module.Layout),
  { loading: () => <Loading /> }
);
const CaseStudy = ({
  pageInfo,
  globalInfo,
  footerInfo,
  locale,
  preview,
}: IPageProps) => {
  return (
    <>
      <Head>
        <title>EastSide | Case Study</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="googlebot" content="noindex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout globalInfo={globalInfo} footerInfo={footerInfo} preview={preview}>
        <div>
          {/* The dynamic blocks will be rendered here */}
          <CaseStudyList
            heroProps={pageInfo.block[0]}
            locale={locale || 'en'}
          />
        </div>
      </Layout>
    </>
  );
};
export async function getStaticProps(context: IContext) {
  let { locale } = context;
  let pageInfo, globalInfo, footerInfo;
  if (!locale) locale = 'en';
  try {
    /* Page Data Fetch */
    const { data: pageData } = await client.query({
      query: PageBySlug('case-study', locale),
    });
    if (pageData.pages.data.length) {
      pageInfo = pageData.pages.data[0].attributes;
    } else {
      return redirectTo500page();
    }
    /* Global Info Fetch */
    globalInfo = await getGlobalInfo(locale, client);
    /* Footer Info Fetch */
    footerInfo = await getFooterInfo(locale, client);
    if (!globalInfo || !footerInfo) return redirectTo500page();
    return {
      props: {
        pageInfo,
        globalInfo,
        footerInfo,
        locale,
        preview: context.preview || false,
      },
      revalidate: context.preview ? 1 : 120,
    };
  } catch (error) {
    return redirectTo500page();
  }
}
export default CaseStudy;
